---
- name: Create OpenShift namespace "{{ openshift_namespace }}"
  tags: [create_namespace]
  kubernetes.core.k8s:
    state: present
    resource_definition:
      apiVersion: project.openshift.io/v1
      kind: Project 
      metadata:
        name: "{{ openshift_namespace }}"

